### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by ByteBaker** [sighol/tree-rs#22]
As part of improving `tree-rs` in the course of the foreseeable future, following tasks are to be completed.

- [x] Refactor the project structure, debloat `main.rs`.
- [x] Add support for `-d` flag.
- [x] Add GitHub CI for `crates.io`
- [x] Add support for `-I` flag.
- [x] Add more test cases and refactor existing ones.
- [ ] Check possibility of and maybe then migrate tests from Python to Rust.
- [x] Add documentation to track features ported from `tree` and the ones for future.
- [ ] Add a template to create issues.
- [ ] Benchmark the code and improve. Currently `tree-rs` seems to be slower than `tree`.
- [ ] Work on issue #14

@sighol please add more items that you think should be here.

**Comment by ByteBaker** [comment]
Hi @sighol,

I've started implementing `-I`, which made me realize that we may have to change the type of `-P` parameter as well.

According to `man tree`:
```
    -P pattern
    List only those files that match the wild-card pattern. You may have multiple -P options. <omitted the rest>

    -I pattern
    Do not list those files that match the wild-card pattern. You may have multiple -I options. See -P above for information on wildcard patterns.
```

Currently, `include_pattern` is defined as: 
```rust
/// List only those files matching <`include_pattern`>
#[clap(short = 'P')]
include_pattern: Option<String>,
```

Which should be changed to
```rust
/// List only those files matching <`include_pattern`>
#[clap(short = 'P')]
include_pattern: Vec<String>,
```

What do you think? I'll define a parameter `exclude_pattern` for `-I` which will have the same signature, but will be used to exlude those that match. What do you think?

**Comment by sighol** [comment]
Thanks! That sounds very reasonable!

**Comment by ByteBaker** [comment]
Tracking #27 which adds support for symlinks through `-l`
